### ISSUE TITLE
Tool won't start

### ISSUE THREAD

**Issue by EMG-Edewolf** [Turbero/7DTD-Mods-Desktop#5] opened 2020-05-26 21:26 UTC
downloaded and put it into a folder on desktop. Start with Admin permission, but on first start an error accures. Message: Game path not found. (Issue found: null). Java starts but nothing else happens.
Logfile attached, thx for working on this.
[7DTD_Mods_Desktop.log](https://github.com/Turbero/7DTD-Mods-Desktop/files/4685102/7DTD_Mods_Desktop.log)

**Comment by EMG-Edewolf** [comment] 2020-05-26 21:34
I tried to set the game- and modpath manually in the config file but now the Java process will start and close a few secs later... Log attached...
[7DTD_Mods_Desktop.log](https://github.com/Turbero/7DTD-Mods-Desktop/files/4685124/7DTD_Mods_Desktop.log)

**Comment by Turbero** [comment] 2020-05-26 21:40
Hi Edewolg

Thanks for your feedback. Good that you could setup the path manually. There's a default path in your windows registry where the tool looks up the game. If not detected for any reason, you can select manually as you did and it will be saved after you open.

However I also managed to reproduce the second problem you faced. I'll figure it out and create a patch as soon as I can hopefully within 24 hours and let you know.

Thanks again.

**Comment by EMG-Edewolf** [comment] 2020-05-26 21:48
Hi Tubero,

thank you for your fast respond. I hope you can solve the problem. I tried to make a questrow and it will work on my local system but when I put it on our server the quests won't work. It seems there is a problem with the "RandomPOIGoto". I don't know where the problem is and I hope when I use your tool to remake the quests it will work on the Server too.

**Comment by Turbero** [comment] 2020-05-26 22:44
Hi EMG.

Regarding your previous issue I fixed it and created version v1.3.0.1. You should be able to download from main page: https://7dtdmodsdesktop.com/download.php.

Regarding your problems in server side, does it return anything specific to understand the conflict with RandomPOIGoto? I have never used a server but I don't think there's any difference.

If possible, also send your file "7DTD_Mods_Desktop_Quests.ini".

**Comment by EMG-Edewolf** [comment] 2020-05-26 22:57
Hi Turbero,
thank you so much! It seems the tool works now.
The Server give a error, but I don't know what this error will tell me...^^
I put it as attachement... Maybe you could help me out. 
[questerror.txt](https://github.com/Turbero/7DTD-Mods-Desktop/files/4685414/questerror.txt)

**Comment by EMG-Edewolf** [comment] 2020-05-26 23:16
I will attach one of the quests I've bulid here too. The other quests follow the same layout. Maybe you see the issue at first sight...
One thing I see is, your tool doesn't support the "FetchFromContainer" entry. Maybe you like to add it in future distributions.
Thank you so much!
[quest.txt](https://github.com/Turbero/7DTD-Mods-Desktop/files/4685459/quest.txt)

**Comment by Turbero** [comment] 2020-05-26 23:28
Good to know your original issue is solved!

Please send me the generated file "7DTD_Mods_Desktop_Quests.ini" not the preview so I can recreate your scenario. Isn't "FetchFromContainer" included in your quest.txt file? Are you referring to something else?

For another thing, German characters sometimes lead to errors when saving or loading the content with the tool but I'll work on that in the next months.

**Comment by EMG-Edewolf** [comment] 2020-05-26 23:39
Actual the "7DTD_Mods_Desktop_Quests.ini" doesn't include the "FetchFromContainer" tag because your tool doesn't give it as choice. The "POIStayWithin" is not aviable to choose at the tool too.
The next Problem that approach is at the rewards, I'm not able to set a custom Item. I have to choose one from the groups in the popup. 
Sorry my english is not good as it schould be... I hope you understand me...

**Comment by Turbero** [comment] 2020-05-26 23:55
Oh sorry! I included support for "FetchFromTreasure" not "FetchFromContainer" as you were asking. My mistake :)

Regarding POIStayWithin and custom items, you're correct I couldn't support it yet but it's in my todo list. Thank you for pointing out!

SInce the original issue was solved I'll close this defect and add those tasks to my list. 

Appreciate your feedback a lot. Many thanks!

**Closed as completed by Turbero** 2020-05-26 23:55 UTC
Labels: bug, fixed

**Comment by EMG-Edewolf** [comment] 2020-05-26 23:57
Yes, the original issue is solved.
Thank you so much.
